# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_food_calories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='name_text',
            new_name='name',
        ),
    ]
