# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180510_2222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
