# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_delete_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('foods', models.ManyToManyField(to='tracker.Food')),
            ],
        ),
    ]
